---
- name: Include global_vars
  include_vars:
    file: '../vars/all.yml'
    name:  global_vars

- name: Set global keybindings
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.desktop.screensaver lock-enabled false
    - gsettings set org.gnome.desktop.screensaver lock-enabled false

    - gsettings set org.gnome.desktop.wm.keybindings cycle-group "[]"
    - gsettings set org.gnome.desktop.wm.keybindings begin-move "[]"
    - gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]"
    - gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]"
    - gsettings set org.gnome.desktop.wm.keybindings begin-resize "[]"
  become: true
  become_user: dev
