---
- name: Include global_vars
  include_vars:
    file: 'defaults/main.yml'
    name:  global_vars

- name: Set global keybindings
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.desktop.wm.keybindings cycle-group "[]"
    - gsettings set org.gnome.desktop.wm.keybindings begin-move "[]"
    - gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]"
    - gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]"
    - gsettings set org.gnome.desktop.wm.keybindings begin-resize "[]"
    - gsettings set org.gnome.desktop.input-sources  sources "[('xkb', 'ch'), ('xkb', 'ch+fr')]"
    - gsettings set org.gnome.desktop.datetime  automatic-timezone true
    - timedatectl set-timezone Europe/Zurich
    - gsettings set org.gnome.desktop.lockdown  disable-lock-screen true
    - gsettings set org.gnome.desktop.screensaver  ubuntu-lock-on-suspend false
  ignore_errors: yes
  become: true
  become_user: '{{ global_vars.user_session }}'


- name: Install some Stuff
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - dconf-tools

