---

- name: Ensure Nodejs is Install
  include_role:
    name: nodejs
  when: not idontwanttorun

- name: Install Angular-cli ( *** warning  ! If it lasts more than 2 minutes! Stop the process and restart the desktop_install script ***  )
  npm:
    name: '@angular/cli'
    global: yes

- name: Instal ncu
  npm:
    name: npm-check-updates
    global: yes


