---
- name: Set WallPapepers
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.desktop.background picture-uri "file:///~/Desktop/jeap-ansible/roles/wallpaper/templates/Ubuntu-Wall.PNG"
  become: true
  become_user: dev
