---
  - name: Include global_vars
    include_vars:
      file: 'defaults/main.yml'
      name:  global_vars

  - debug:
      msg: "Home path {{ global_vars.home_path }}"

  - name: Check if maven is installed
    command: "{{ item }}"
    with_items:
      - mvn -version
    register: maven_result
    ignore_errors: True

  - debug:
      var: maven_result

  - name: "Find if failed  maven command"
    debug:
      var: maven_result|json_query('results[*].[failed] | [0]')

  - name: "test maven_present"
    debug:
      var: maven_result.results[0].failed

  - import_tasks: tasks/maven_install.yml
    when: maven_result.results[0].failed
