---
  - name: Include global_vars
    include_vars:
      file: 'defaults/main.yml'
      name:  global_vars

  - debug:
      msg: "Home path {{ global_vars.home_path }}/maven"

  - name: Check if maven is installed
    stat:
      path={{ global_vars.home_path }}/maven
    register: maven_present


  - debug:
      msg: "Maven not Installed"
    when:   maven_present.stat.exists

  - import_tasks: tasks/maven_install.yml
    when: not  maven_present.stat.exists
