---
  - name: Include global_vars
    include_vars:
      file: '../vars/all.yml'
      name:  global_vars

  - debug:
      msg: "Home path {{ global_vars.home_path }}"

  - name: Check if maven is installed
    stat:
      path={{maven_destination_directory}}
    register: maven_present

  - debug:
      msg: "Java not Installed"
    when:  maven_present.stat.exists

  - import_tasks: tasks/maven_install.yml
    when: not maven_present.stat.exists