---
  - name: Create destination directory
    file:
      path: "{{ maven_destination_directory }}"
      owner: '{{ global_vars.user_session }}'
      group: '{{ global_vars.user_session }}'
      mode: 0755
      state: directory

  - name: Download and untar the maven binary file
    unarchive:
      src: http://apache.mirrors.spacedump.net/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
      dest: "{{ maven_destination_directory }}"
      remote_src: yes
      owner: '{{ global_vars.user_session }}'
      group: '{{ global_vars.user_session }}'
      mode: 0755


  - name: Create a symlink to mvn
    file:
      src: "{{ maven_destination_directory }}/apache-maven-{{ maven_version }}/bin/mvn"
      dest: /usr/local/bin/mvn
      owner: '{{ global_vars.user_session }}'
      group: '{{ global_vars.user_session }}'
      state: link

  - name: Ensure M2_HOME is sourced from the .profile
    blockinfile:
      dest: "~/.profile"
      block: |
       M2_HOME="{{maven_name}}"
       PATH="$M2_HOME/bin:$PATH"
      marker: '# {mark}  MANAGED BLOCK - exporte M2_HOME'
      insertbefore: EOF
      create: yes

  - name: Fix ownership
    file: state=directory path={{maven_m2}} owner='{{ global_vars.user_session }}' group='{{ global_vars.user_session }}' recurse=yes mode=0755


  - name: Add M2_HOME on etc/environment
    lineinfile:
        dest: /etc/environment
        insertafter: EOF
        line: 'M2_HOME="{{ maven_destination_directory }}/apache-maven-{{ maven_version }}"'



  - name: M2_HOME Set permission to dev user
    command: "{{ item }}"
    with_items:
        - chmod -R 755 {{ maven_destination_directory }}/apache-maven-{{ maven_version }}
        - chown -R '{{ global_vars.user_session }}' {{ maven_destination_directory }}/apache-maven-{{ maven_version }}
