---

  - name: Create JAVA_HOME folder
    file: state=directory path={{download_folder}} owner=dev group=dev recurse=yes mode=0755

  - name: Download Java from url
    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"
    register: java_out

  # show the content of intellij_out var
  - debug: var=java_out



  - name: Fix ownership
    file: state=directory path={{java_install_dir}} owner=dev group=dev recurse=yes

  - name: Unpack archive
    command: "tar -zxf {{java_archive}} --strip 1 -C {{java_install_dir}} "

  - name: Clean up
    file: state=absent path={{java_archive}}

  - name: Ensure JAVA_HOME to export on .bashrc
    blockinfile:
      dest: "/home/dev/.bashrc"
      block: |
        export JAVA_HOME={{java_install_dir}}
      marker: '# {mark}  MANAGED BLOCK - exporte Custom Variable'
      insertbefore: EOF
      create: yes

  - name: Ensure JAVA_HOME  to export on .profile
    blockinfile:
      dest: "/home/dev/.profile"
      block: |
       JAVA_HOME="{{java_install_dir}}"
       PATH="$JAVA_HOME/jre/bin:$PATH"
      marker: '# {mark}  MANAGED BLOCK - exporte JAVA_HOME'
      insertbefore: EOF
      create: yes

  - name: Rename default cacert to cacert old
    command: mv {{cacerts_path}}/cacerts {{cacerts_path}}/cacerts_old

  - name: Replace default Cacert file to bit version
    copy:
       src:   certificates/cacerts
       dest: '{{cacerts_path}}'
       owner: dev
       group: dev
       mode: 0755
       backup: yes

  - name: Add JAVA_HOME on etc/environment
    lineinfile:
        dest: /etc/environment
        insertafter: EOF
        line: 'JAVA_HOME={{java_install_dir}}'


  - name: Java Set permission to dev user
    command: "{{ item }}"
    with_items:
      - chmod -R 755 {{java_install_dir}}
      - chown -R dev {{java_install_dir}}





