---
  - name: Include global_vars
    include_vars:
      file: 'defaults/main.yml'
      name:  global_vars

  - debug:
      msg: "Home path {{ global_vars.home_path }}"

  - name: Check if java is installed
    command: "{{ item }}"
    with_items:
      - java --version
    register: java_present
    ignore_errors: True

  - debug:
      var: java_present

  - debug:
      msg: "Java not Installed"
    when:  java_present.failed

  - import_tasks: tasks/java_install.yml
    when: java_present.failed