---

- name: create kitematic install directory
  file:
    dest: "{{ kitematic_Home }}"
    group: '{{ global_vars.user_session }}'
    owner: '{{ global_vars.user_session }}'
    mode: 0755
    state: directory

- name: Download kitematic
  get_url: url={{kitematic_url}} dest={{kitematic_Home}}
  register: kitematic_out

- name: Unarchive
  unarchive:
    copy: no
    src: "{{kitematic_Home}}/Kitematic-{{kitematic_version}}-Ubuntu.zip"
    dest: "{{kitematic_Home}}"


- name: kitematic Set permission to dev user
  command: "{{ item }}"
  with_items:
    - chmod -R 755 {{kitematic_Home}}
    - chown -R '{{ global_vars.user_session }}' {{kitematic_Home}}


- name: Install kitematic .deb package
  apt:
    deb: ~/development/kitematic/dist/Kitematic_{{kitematic_version}}_amd64.deb
