---
  - name: Check if kitematic is installed
    stat:
      path={{ kitematic_Home }}
    register: kitematic_present

  - debug:
      msg: "Java not Installed"
    when:  kitematic_present.stat.exists

  - import_tasks: tasks/kitematic_install.yml
    when: not kitematic_present.stat.exists
